//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.DeviceTbls = new HashSet<DeviceTbl>();
            this.Organisations = new HashSet<Organisation>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> HasChangePwd { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<DeviceTbl> DeviceTbls { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
    }
}
