//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.AppUsers = new HashSet<AppUser>();
            this.DeviceTbls = new HashSet<DeviceTbl>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<DeviceTbl> DeviceTbls { get; set; }
    }
}
