//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.EventFeedbacks = new HashSet<EventFeedback>();
        }
    
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string AccountNumber { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Comment { get; set; }
        public string FeedBackVal { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<EventFeedback> EventFeedbacks { get; set; }
    }
}
