//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FeedBackDBEntities : DbContext
    {
        public FeedBackDBEntities()
            : base("name=FeedBackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DeviceTbl> DeviceTbls { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<SmileyAction> SmileyActions { get; set; }
        public DbSet<IconGallery> IconGalleries { get; set; }
        public DbSet<LabelSetting> LabelSettings { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventFeedback> EventFeedbacks { get; set; }
        public DbSet<EventMetric> EventMetrics { get; set; }
        public DbSet<HomeSetting> HomeSettings { get; set; }
        public DbSet<MetricElement> MetricElements { get; set; }
        public DbSet<EventDevice> EventDevices { get; set; }
    }
}
