//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventFeedbacks = new HashSet<EventFeedback>();
            this.EventMetrics = new HashSet<EventMetric>();
            this.HomeSettings = new HashSet<HomeSetting>();
            this.MetricElements = new HashSet<MetricElement>();
            this.EventDevices = new HashSet<EventDevice>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Question { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<EventFeedback> EventFeedbacks { get; set; }
        public virtual ICollection<EventMetric> EventMetrics { get; set; }
        public virtual ICollection<HomeSetting> HomeSettings { get; set; }
        public virtual ICollection<MetricElement> MetricElements { get; set; }
        public virtual ICollection<EventDevice> EventDevices { get; set; }
    }
}
