//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricElement
    {
        public MetricElement()
        {
            this.EventFeedbacks = new HashSet<EventFeedback>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventMetricID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<EventFeedback> EventFeedbacks { get; set; }
        public virtual EventMetric EventMetric { get; set; }
    }
}
