//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
