//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFeedbackSoln.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string ServiceIcon { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> ServiceCatId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DatedAdded { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
